In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
import pickle

In [4]:
import pandas as pd

In [5]:
runtimes = {}

In [6]:
with open("runtimes.log") as f:
    lines = f.readlines()
    for l in lines:
        a = l.split(" ")
        n = a[2]
        if not n in runtimes.keys():
            runtimes[n] = []
        timeTaken = a[5]
        runtimes[n] += [timeTaken]

In [8]:
with open("runtimes.pkl", "rb") as f:
    r = pickle.load(f)

In [9]:
r

{'6': ['21',
  '21',
  '0',
  '1',
  '1',
  '0',
  '2',
  '0',
  '0',
  '1',
  '0',
  '0',
  '21',
  '1',
  '1',
  '1',
  '0',
  '2',
  '1',
  '0',
  '0',
  '1',
  '0',
  '22',
  '1',
  '1',
  '1',
  '0',
  '2',
  '1',
  '0',
  '1',
  '0',
  '1'],
 '18': ['28',
  '3',
  '2',
  '1',
  '2',
  '2',
  '1',
  '1',
  '1',
  '1',
  '1',
  '22',
  '2',
  '2',
  '1',
  '1',
  '2',
  '1',
  '1',
  '1',
  '1',
  '0',
  '23',
  '3',
  '2',
  '1',
  '2',
  '1',
  '1',
  '0',
  '1',
  '1',
  '1'],
 '54': ['39',
  '5',
  '3',
  '3',
  '3',
  '2',
  '2',
  '2',
  '2',
  '1',
  '2',
  '44',
  '3',
  '2',
  '1',
  '1',
  '2',
  '1',
  '2',
  '1',
  '1',
  '1',
  '45',
  '7',
  '8',
  '7',
  '6',
  '5',
  '4',
  '4',
  '3',
  '3',
  '3'],
 '162': ['36',
  '5',
  '4',
  '3',
  '2',
  '3',
  '2',
  '1',
  '2',
  '1',
  '2',
  '38',
  '5',
  '3',
  '4',
  '3',
  '3',
  '3',
  '2',
  '3',
  '3',
  '2',
  '41',
  '5',
  '4',
  '3',
  '3',
  '3',
  '2',
  '2',
  '3',
  '2',
  '2'],
 '486': ['56',
  '9',
  '8',
  '7',
  '6',
  '6',
  '11',
  '8',
  '6',
  '7',
  '6',
  '74',
  '9',
  '7',
  '5',
  '6',
  '5',
  '7',
  '7',
  '8',
  '7',
  '6',
  '55',
  '10',
  '7',
  '7',
  '6',
  '6',
  '8',
  '7',
  '8',
  '8',
  '8'],
 '1458': ['80',
  '23',
  '26',
  '22',
  '19',
  '19',
  '28',
  '13',
  '13',
  '13',
  '12',
  '106',
  '37',
  '33',
  '27',
  '30',
  '26',
  '32',
  '14',
  '14',
  '14',
  '14',
  '88',
  '26',
  '29',
  '28',
  '24',
  '25',
  '46',
  '20',
  '18',
  '17',
  '17'],
 '1000': ['57', '14', '20', '21', '14', '13', '12', '13', '13', '18', '10']}

In [10]:
r_df = pd.DataFrame.from_dict(r)

ValueError: arrays must all be same length

In [19]:
data = list(r.keys())

In [20]:
type(data)

list

In [50]:
d = {'col1': list(r.keys())}

In [51]:
df = pd.DataFrame(data = d, index = list(r.keys()))

In [52]:
df['means'] = range(len(list(r.keys())))

In [53]:
minObsLen = 200

for key in r.keys():
    minObsLen = min(minObsLen, len(r[key]))

for i in range(minObsLen):
    
    obs = []
    
    for key in r.keys():
        obs += [ float(runtimes[key][i]) ]
    
    df[f"obs{i}"] = obs

In [54]:
obsColumns = [ f"obs{i}" for i in range(minObsLen) ]

In [62]:
df

,col1,means,obs0,obs1,obs2,obs3,obs4,obs5,obs6,obs7,obs8,obs9,obs10,sum
6,6,0,21.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,NaN
18,18,1,28.0,3.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN
54,54,2,39.0,5.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,1.0,2.0,NaN
162,162,3,36.0,5.0,4.0,3.0,2.0,3.0,2.0,1.0,2.0,1.0,2.0,NaN
486,486,4,56.0,9.0,8.0,7.0,6.0,6.0,11.0,8.0,6.0,7.0,6.0,NaN
1458,1458,5,80.0,23.0,26.0,22.0,19.0,19.0,28.0,13.0,13.0,13.0,12.0,NaN
1000,1000,6,57.0,14.0,20.0,21.0,14.0,13.0,12.0,13.0,13.0,18.0,10.0,NaN

In [64]:
(df[obsColumns].sum("column").tolist())

ValueError: No axis named column for object type DataFrame

In [46]:
df['means'] = df['sum'] / minObsLen

In [56]:
df['sum']

6      NaN
18     NaN
54     NaN
162    NaN
486    NaN
1458   NaN
1000   NaN
Name: sum, dtype: float64